/**
 * Central icon registry for ClickNComply Group.
 *
 * Single source of truth for every icon used in the platform. Lucide React only —
 * never mix icon libraries (causes the "cheap mixed look").
 *
 * To swap an icon globally, change it here. Every component imports from this file.
 */

import {
  // Industries — Construction & Built Environment
  Wrench,
  Construction,
  Hammer,
  Home,
  PaintRoller,
  Drill,
  // Industries — M&E Services
  Zap,
  Droplet,
  Wind,
  Flame,
  Bell,
  CableCar,
  // Industries — Specialist Construction
  TrainTrack,
  Plane,
  Ship,
  Antenna,
  // Industries — Manufacturing & Engineering
  Factory,
  Cpu,
  Cog,
  // Industries — Facilities & Property
  Sparkles as SparklesIcon,
  Trees,
  Bug,
  // Industries — Hospitality, Food & Retail
  ChefHat,
  UtensilsCrossed,
  ShoppingBag,
  Coffee,
  // Industries — Tech & Digital
  Code2,
  Cloud,
  Server,
  // Industries — Professional Services
  Briefcase,
  ClipboardList,
  ScrollText,
  // Industries — Healthcare
  Stethoscope,
  HeartPulse,
  // Industries — Logistics
  Truck,
  Package,
  Warehouse,
  // Industries — Other
  GraduationCap,
  Heart,
  Building,
  Building2,
  Landmark,

  // Frameworks
  Award,
  HardHat,
  Leaf,
  Lock,
  Scale,
  ShieldCheck,

  // Tools
  ShieldAlert,
  ClipboardCheck,
  MoveVertical,
  Users,
  Folder,
  FolderOpen,

  // UI actions
  Sparkles,
  Plus,
  Download,
  Upload,
  Settings,
  LogOut,
  CircleUser,
  Search,
  Filter,
  Pencil,
  Trash2,
  Check,
  CircleCheck,
  Clock,
  CircleX,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronRight,
  ExternalLink,
  Mail,
  Copy,
  FileText,
  FilePlus2,
  Eye,
  EyeOff,
  type LucideIcon,
} from "lucide-react";

// Re-export commonly-used icons for direct import elsewhere
export {
  Sparkles,
  Plus,
  Download,
  Upload,
  Settings,
  LogOut,
  CircleUser,
  Search,
  Filter,
  Pencil,
  Trash2,
  Check,
  CircleCheck,
  Clock,
  CircleX,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronRight,
  ExternalLink,
  Mail,
  Copy,
  FileText,
  FilePlus2,
  Eye,
  EyeOff,
  ShieldAlert,
  ClipboardCheck,
  MoveVertical,
  Users,
  ShieldCheck,
  Folder,
  FolderOpen,
  Award,
  HardHat,
  Building2,
  Leaf,
  HeartPulse,
  Lock,
  Scale,
  ChefHat,
  Factory,
  type LucideIcon,
};

// Industry icon registry — keyed by industry slug (matches src/lib/industries.ts)
export const INDUSTRY_ICONS: Record<string, LucideIcon> = {
  // Construction & Built Environment
  "arch-metalwork": Wrench,
  "structural-steel": Wrench,
  "steel-erection": Construction,
  "civils-groundworks": Construction,
  "civils-drainage": Droplet,
  "civils-highways": TrainTrack,
  "civils-utilities": Zap,
  "concrete": Construction,
  "demolition": Hammer,
  "asbestos": ShieldAlert,
  "roofing-commercial": Home,
  "roofing-residential": Home,
  "cladding": Building2,
  "glazing": Building2,
  "plastering": PaintRoller,
  "painting": PaintRoller,
  "brickwork": Hammer,
  "carpentry": Hammer,
  "tiling": Hammer,
  "flooring": Hammer,
  "insulation": Building2,
  "scaffolding": Construction,
  "plant-operators": Truck,
  "plant-hire": Truck,
  // M&E Services
  "electrical-commercial": Zap,
  "electrical-industrial": Zap,
  "electrical-domestic": Zap,
  "electrical-testing": Zap,
  "plumbing": Droplet,
  "heating-gas": Flame,
  "ventilation": Wind,
  "aircon": Wind,
  "refrigeration": Wind,
  "fire-sprinkler": Droplet,
  "fire-alarm": Bell,
  "security": Lock,
  "bms": Cpu,
  "av-data": CableCar,
  // Specialist Construction
  "rail": TrainTrack,
  "aviation": Plane,
  "marine": Ship,
  "telecoms": Antenna,
  "substations": Zap,
  "overhead-lines": Zap,
  "wind-turbine": Wind,
  "solar-pv": Zap,
  "ev-charging": Zap,
  "heritage": Landmark,
  // Manufacturing & Engineering
  "heavy-engineering": Factory,
  "light-fabrication": Drill,
  "precision-engineering": Cog,
  "plastics-composites": Factory,
  "coatings": PaintRoller,
  "electronics": Cpu,
  "aerospace": Plane,
  "automotive": Truck,
  "food-production": ChefHat,
  // Facilities & Property
  "facilities-management": Building2,
  "cleaning": SparklesIcon,
  "landscaping": Trees,
  "pest-control": Bug,
  "property-maintenance": Building,
  "estate-management": Landmark,
  // Hospitality, Food & Retail
  "catering": UtensilsCrossed,
  "hospitality": Coffee,
  "retail": ShoppingBag,
  "food-packaging": Package,
  // Tech & Digital
  "saas": Code2,
  "msp-it": Server,
  "hosting-cloud": Cloud,
  "digital-agency": Code2,
  "cybersecurity": Lock,
  // Professional Services
  "architecture": Building,
  "engineering-consultancy": Briefcase,
  "qs-cost": ScrollText,
  "legal": Scale,
  "accounting": ScrollText,
  "recruitment": Briefcase,
  "hs-consultancy": ClipboardList,
  // Healthcare
  "dental": Stethoscope,
  "veterinary": Stethoscope,
  "medical": Stethoscope,
  "care-home": HeartPulse,
  "medical-devices": HeartPulse,
  // Logistics
  "haulage": Truck,
  "warehousing": Warehouse,
  "couriers": Package,
  "distribution": Package,
  // Other
  "education": GraduationCap,
  "charity": Heart,
  "public-sector": Landmark,
  "other": Briefcase,
};

// Framework icon registry — keyed by framework slug
export const FRAMEWORK_ICONS: Record<string, LucideIcon> = {
  "iso-9001": Award,
  "bs-en-1090": Factory,
  "chas": HardHat,
  "constructionline": Building2,
  "iso-14001": Leaf,
  "iso-45001": HeartPulse,
  "iso-27001": Lock,
  "cyber-essentials": ShieldCheck,
  "gdpr": Scale,
  "haccp": ChefHat,
  "cdm-2015": HardHat,
};
